### ISSUE TITLE
Cannot be done with success on executing `mix ecto.setup` command

### ISSUE THREAD

**Issue by ysaito8015** [piacerex/communitex#35]
I try to run the communitex app on the environment below
- elixir 1.10.1, phoniex 1.5.13, node 12.x
    - [docker-compose.yml](https://github.com/ysaito8015/communitex/blob/ysaito/dockernization/docker-compose.yml)
    - [Dockerfile](https://github.com/ysaito8015/communitex/blob/ysaito/dockernization/Dockerfile)

But it cannot be done with success on executing `mix ecto.setup` command, there is an error.

```
You have configured application :sphere in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :sphere exists or remove the configuration.
```

- verbose error messages are [here](https://gist.github.com/ysaito8015/660f38f43109999ac34a90494992257f)

Did I miss something?

**Comment by piacerex** [comment]
This log means that the startup was successful.

This error was well known, it reason is that the config file is not good enough, I'll fix it.

If Phoenix is not running, please let me know.
