### ISSUE TITLE
The "Roll" pull-down was empty

### ISSUE THREAD

**Issue by piacerex** [piacerex/communitex#9]
@rioorinoco As shown below, the "Roll" pull-down was empty at the Grants initial registration:
![image](https://user-images.githubusercontent.com/18749428/131837536-154e3a20-7b2c-49bf-a6ca-c7108899dd4e.png)

What is the cause?

**Comment by rioorinoco** [comment]
Please login as a SystemAdmin.

**Comment by piacerex** [comment]
Oh, I see.
Please implement with a page display that prompts you to log in with SystemAdmin.

**Comment by piacerex** [comment]
I implemented that prompts you to log in with *Admin if the logged-in user is not *Admin.
